---
swagger: "2.0"
info:
  description: "A sample API that uses a petstore as an example to demonstrate features\
    \ in the swagger-2.0 specification"
  version: "1.0.0"
  title: "Swagger organization.data.sabius-alpha"
  termsOfService: "http://helloreverb.com/terms/"
  contact:
    name: "Swagger API team"
    url: "http://swagger.io"
    email: "foo@example.com"
  license:
    name: "MIT"
    url: "http://opensource.org/licenses/MIT"
host: "localhost:8080"
basePath: "/api/v1"
schemes:
- "http"
- "https"
consumes:
- "application/json"
produces:
- "application/json"
paths:
  /:
    get:
      tags:
      - "render"
      description: "Returns all renders"
      operationId: "get"
      parameters: []
      responses:
        200:
          description: "Render response"
          schema:
            type: "array"
            title: "Renders"
            items:
              $ref: "#/definitions/Render"
        500:
          description: "Internal Server Error"
      x-swagger-router-controller: "Render"
definitions:
  Render:
    type: "object"
    properties:
      id:
        type: "string"
      model:
        type: "string"
      view:
        type: "string"
      ctrl:
        type: "string"
      type:
        type: "string"
